Use target branch clone instead of shallow clone
Since shallow clone does not include historical commits, one cannot checkout to target branch. This PR suggest to use

```
git clone  --single-branch --branch v2.21.5-1 https://github.com/NVIDIA/nccl.git
```
instead.

```
mlkeita on  main [✘+?]
➜ git clone --depth=1 https://github.com/NVIDIA/nccl.git
Cloning into 'nccl'...
remote: Enumerating objects: 216, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 216 (delta 26), reused 90 (delta 16), pack-reused 0
Receiving objects: 100% (216/216), 496.14 KiB | 7.09 MiB/s, done.
Resolving deltas: 100% (26/26), done.

nccl …
➜ ls
LICENSE.txt Makefile    README.md   ext-net     ext-tuner   makefiles   pkg         src

nccl on  master
➜ git checkout v2.21.5-1
error: pathspec 'v2.21.5-1' did not match any file(s) known to git
```

Co-authored-by: Daisuke Miyamoto <midaisuk@gmail.com>